name: Build and Upload Artifact

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools
          pip install -r requirements.txt

      # Build the project
      - name: Build project
        run: |
          mkdir -p build
          # Replace the following command with your actual build command
          echo "Building project..." > build/output.txt

      # Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build/
